### ISSUE TITLE
在win系统上无法运行项目

### ISSUE THREAD

**Issue by zuitai** [run-bigpig/svrw#2]
![image](https://github.com/run-bigpig/svrw/assets/32135385/12397574-1744-481f-ab11-488e2fadbbcd)

按照介绍文档上的流程走到了./svrw  运行项目的这一步  但在windows11系统上出现了让选择打开方式，试了多种选择打开方式均不能运行

**Comment by run-bigpig** [comment]
windows 环境下需要编译为 .exe 格式的文件  
go build -o svrw.exe cmd/main.go
